### ISSUE TITLE
Run make test-ios-safari test,no test executed

### ISSUE THREAD

**Issue by huwangtao123** [macaca-sample/sample-nodejs#12]
I am following the steps listed here https://macacajs.github.io/zh/quick-start 
when i run the test-ios-safari, 0 test have been executed, with the warrning 
>> (node:53112) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Looks like the os.tmpDir has still been used in macaca-wd. 
./node_modules/macaca-wd/wd/lib/tmp.js:42:  tmpDir = os.tmpDir || _getTMPDir,

The detail log is listed 
$ make test-ios-safari
macaca doctor

  macaca-doctor version: 2.0.3

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.9.1

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.26.2

  Android checklist:

  JAVA version is `1.8.0_152`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/Tao/Library/Android/sdk`
  Platforms is set to `/Users/Tao/Library/Android/sdk/platforms/android-27`
  ADB tool is set to `/Users/Tao/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.3

  Installed driver list:

  ios: 2.0.29

browser=safari macaca run --verbose --reporter macaca-reporter -d ./macaca-test/mobile-browser-sample.test.js
>> index.js:18:12 [master] pid:53110 webdriver server start with config:
 { port: 3456,
  verbose: false,
  always: true,
  window: true,
  ip: '192.168.29.218',
  host: 'Taos-MBP.T-mobile.com',
  loaded_time: '2017-11-14 00:25:13' }
>> middlewares.js:17:10 [master] pid:53110 base middlewares attached
>> router.js:133:10 [master] pid:53110 router set
>> webdriver sdk launched
[ '/Users/Tao/workspace/sample-nodejs/node_modules/.bin/mocha',
  './macaca-test/mobile-browser-sample.test.js',
  '--reporter',
  'macaca-reporter',
  '--colors',
  '--verbose' ]
>>

>>
  0 passing (1ms)

>> >> reporter generated: /Users/Tao/workspace/sample-nodejs/reports/index.html

>> (node:53112) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

>> Test completed!

Please let me know if these sample test will still be maintain. Since i also have the issue with the app test. 

Thank you very much
Tao

**Comment by huwangtao123** [comment]
Any update on this? 
I have the issue on both IOS Safari and Android Chrome. Except the 
` (node:7472) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.` I don't see any other log for investigation 

Also, I notice the build has failed in Travis CI. I assume it means the tests are failed.

**Comment by xudafeng** [comment]
@huwangtao123 how about the command `make test-ios` ?

**Comment by huwangtao123** [comment]
@xudafeng  Sorry for the late reply.

I did rerun all the tests, the summary running result in my local mac are listed
* make test-ios all 8 tests are passing 
* make test-android, 4 tests failed, 4 test passing
* make test-ios-safari, make test-android-chrome, no test have been executed.
    Error:
    >> (node:6656) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() 
    instead.
