### ISSUE TITLE
I can not connect to my phone(android platform)！

### ISSUE THREAD

**Issue by forgsgit** [macaca-sample/sample-nodejs#8]
I have built a macaca environment
`
 Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.10.2

  iOS checklist:

  Xcode is uninstalled
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.24.0

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/lijingjing/Documents/android-sdk-macosx`
  Platforms is set to `/Users/lijingjing/Documents/android-sdk-macosx/platforms/android-25`
  ADB tool is set to `/Users/lijingjing/Documents/android-sdk-macosx/platform-tools/adb`
  gradle is installed, version: 4.0

  Installed driver list:

  android: 2.0.31
  chrome: 1.0.6
  ios: 2.0.23
`
When I run the program, the following exception is thrown：

`
>> uiautomator-client.js:56:14 [master] pid:6408 INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.macaca.android.testing.test/android.support.test.runner.AndroidJUnitRunner}

>> uiautomator-client.js:56:14 [master] pid:6408 INSTRUMENTATION_STATUS_CODE: -1

>> uiautomator-client.js:56:14 [master] pid:6408 android.util.AndroidException: INSTRUMENTATION_FAILED: com.macaca.android.testing.test/android.support.test.runner.AndroidJUnitRunner

>> uiautomator-client.js:56:14 [master] pid:6408 	at com.android.commands.am.Am.runInstrument(Am.java:676)

>> uiautomator-client.js:56:14 [master] pid:6408 	at com.android.commands.am.Am.run(Am.java:119)
	at com.android.commands.am.Am.main(Am.java:82)
>> uiautomator-client.js:56:14 [master] pid:6408 
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:235)

>> uiautomator-client.js:56:14 [master] pid:6408 	at dalvik.system.NativeStart.main(Native Method)
`
How do i solve this problem?

**Comment by xudafeng** [comment]
update driver
